### ISSUE TITLE
p0wd3r - Malicious attackers can perform a DoS attack by executing Router.approve in advance.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#346]
p0wd3r

high

# Malicious attackers can perform a DoS attack by executing Router.approve in advance.
## Summary
Malicious attackers can perform a DoS attack by executing `Router.approve` in advance.
## Vulnerability Detail
The protocol has added the `approve` public function in `PeripheryPayments`, which calls `safeApprove`.
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/utils/PeripheryPayments.sol#L35-L37
```solidity
    function approve(IERC20 token, address to, uint256 amount) public payable {
        token.safeApprove(to, amount);
    }
```

`safeApprove` only allows the allowance to change from 0 to non-zero, not from non-zero to another non-zero value.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.1/contracts/token/ERC20/utils/SafeERC20.sol#L39-L60
```solidity
    /**
     * @dev Deprecated. This function has issues similar to the ones found in
     * {IERC20-approve}, and its usage is discouraged.
     *
     * Whenever possible, use {safeIncreaseAllowance} and
     * {safeDecreaseAllowance} instead.
     */
    function safeApprove(
        IERC20 token,
        address spender,
        uint256 value
    ) internal {
        // safeApprove should only be called when setting an initial allowance,
        // or when resetting it to zero. To increase and decrease it, use
        // 'safeIncreaseAllowance' and 'safeDecreaseAllowance'
        require(
            (value == 0) || (token.allowance(address(this), spender) == 0),
            "SafeERC20: approve from non-zero to non-zero allowance"
        );
        _callOptionalReturn(token, abi.encodeWithSelector(token.approve.selector, spender, value));
    }
```

In the `_deposit` function of the Router, the `approve` function is called.
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouterBase.sol#L60-L70
```solidity
    function _deposit(
        ILMPVault vault,
        address to,
        uint256 amount,
        uint256 minSharesOut
    ) internal returns (uint256 sharesOut) {
        approve(IERC20(vault.asset()), address(vault), amount);
        if ((sharesOut = vault.deposit(amount, to)) < minSharesOut) {
            revert MinSharesError();
        }
    }
```

Since `approve` is a public function, an attacker can execute `approve` once before a user's deposit, making the allowance non-zero. When the user tries to deposit, because the allowance is non-zero, the `approve` function will revert, preventing the user from completing the deposit.

Code PoC:
```diff
diff --git a/v2-core-audit-2023-07-14/test/vault/LMPVaultRouter.t.sol b/v2-core-audit-2023-07-14/test/vault/LMPVaultRouter.t.sol
index 93809f8..71b2e27 100644
--- a/v2-core-audit-2023-07-14/test/vault/LMPVaultRouter.t.sol
+++ b/v2-core-audit-2023-07-14/test/vault/LMPVaultRouter.t.sol
@@ -116,7 +116,7 @@ contract LMPVaultRouterTest is BaseTest {
     }

     // TODO: fuzzing
-    function test_deposit() public {
+    function test_deposit_after_approve() public {
         uint256 amount = depositAmount; // TODO: fuzz
         baseAsset.approve(address(lmpVaultRouter), amount);

@@ -127,6 +127,7 @@ contract LMPVaultRouterTest is BaseTest {
         lmpVaultRouter.deposit(lmpVault, address(this), amount, minSharesExpected);

         // -- now do a successful scenario -- //
+        lmpVaultRouter.approve(baseAsset, address(lmpVault), amount);
         _deposit(lmpVault, amount);
     }
```

```shell
forge test --mt 'test_deposit_after_approve' -vv
[⠑] Compiling...
No files changed, compilation skipped

Running 1 test for test/vault/LMPVaultRouter.t.sol:LMPVaultRouterTest
[FAIL. Reason: SafeERC20: approve from non-zero to non-zero allowance] test_deposit_after_approve() (gas: 297037)
Test result: FAILED. 0 passed; 1 failed; finished in 893.76ms

Failing tests:
Encountered 1 failing test in test/vault/LMPVaultRouter.t.sol:LMPVaultRouterTest
[FAIL. Reason: SafeERC20: approve from non-zero to non-zero allowance] test_deposit_after_approve() (gas: 297037)

Encountered a total of 1 failing tests, 0 tests succeeded
```
## Impact
Performing a DoS attack on the core functionality of the protocol.
## Code Snippet
- https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/utils/PeripheryPayments.sol#L35-L37
- https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.1/contracts/token/ERC20/utils/SafeERC20.sol#L39-L60
- https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVaultRouterBase.sol#L60-L70
## Tool used

Manual Review

## Recommendation

Since `safeApprove` is already deprecated, it is recommended to use `safeIncreaseAllowance` as a replacement for `safeApprove`.

**Comment by 0xdeadbeef0x** [comment]
Escalate

I am escalating this to be low because:
1. `LMPVaultRouterBase` is `MultiCall`. A depositor can approve to zero at the same transaction and successfully deposit/mint without getting DOSed 
2. According to current Sherlock docs a DOS is not considered valid if is less then one year. An attacker would need to front-run every transaction of the target for a year (which could be avoided by front-running the attacker or submitting the transaction through flashbots). 
3. No clear profit for the attacker. Seems like constant front-running would be more expensive then any potential profit

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I am escalating this to be low because:
> 1. `LMPVaultRouterBase` is `MultiCall`. A depositor can approve to zero at the same transaction and successfully deposit/mint without getting DOSed 
> 2. According to current Sherlock docs a DOS is not considered valid if is less then one year. An attacker would need to front-run every transaction of the target for a year (which could be avoided by front-running the attacker or submitting the transaction through flashbots). 
> 3. No clear profit for the attacker. Seems like constant front-running would be more expensive then any potential profit
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
> Escalate
> 
> I am escalating this to be low because:
> 
> 1. `LMPVaultRouterBase` is `MultiCall`. A depositor can approve to zero at the same transaction and successfully deposit/mint without getting DOSed
> 2. According to current Sherlock docs a DOS is not considered valid if is less then one year. An attacker would need to front-run every transaction of the target for a year (which could be avoided by front-running the attacker or submitting the transaction through flashbots).
> 3. No clear profit for the attacker. Seems like constant front-running would be more expensive then any potential profit

The minting function is the core contract functionality of any Router. A router contract without the capability to properly mint shares would be rendered useless. Per the Sherlock judging rules, this issue is a Medium/High.

> https://docs.sherlock.xyz/audits/judging/judging#v.-how-to-identify-a-medium-issue
>
> - Breaks core contract functionality, rendering the contract useless (should not be easily replaced without loss of funds) or leading to unknown potential exploits/loss of funds. 

The contract must be redeployed with the bug fixed. If the bug exists, any malicious user could perform a DOS against the minting function anytime they wish. Thus, it is considered as a permanent DOS.

Apart from breaking the core contract functionality, it can also potentially lead to a loss of assets. The callers who are the external protocols integrated with Tokemak's routers or Tokemak's users encounter issues when attempting to mint shares, leading to fewer assets being invested into the vault. This, in turn, leads to fewer fees being collected as fewer assets can be deployed to the external market for returns.

If there is no clear profit for the attacker, it does not mean that the issue should be Low. The Sherlock judging rules allow such a scenario as a Medium provided other criteria are met. In this case, the severity of this issue is Medium, which the Lead Judge correctly judges this issue:

> https://docs.sherlock.xyz/audits/judging/judging#v.-how-to-identify-a-medium-issue
>
> - No profit for the attacker at a considerable cost

To mitigate this issue, it is not right to ask the depositors always to approve zero before the deposit to prevent being DOSed by malicious actors. Users expect the protocol team to implement a deposit feature that works out of the box. Similarly, users should not be expected to pay higher gas fees or use flashbots to avoid being front-run by malicious actors. This means that the users incur additional costs.

Thus, this issue is a valid Medium.

**Comment by 0xdeadbeef0x** [comment]
>  router contract without the capability to properly mint shares would be rendered useless

The router has the capability to mint shares. The MultiCall is expected to be used not only for approve but also for other operations such as refunding excess eth. Additionally, if the protocol does want to fix the issue the router can be easily replaced without any loss of funds since the router does not hold shares.

>  Any malicious user could perform a DOS against the minting function anytime they wish. Thus, it is considered as a permanent DOS. 

It is not considered permanent DOS because the user is not DOSed. They can at any time use the MultiCall or front-run attacker or use flashbots.

ALSO Its important to note that this is a router used for user convenience. A user can call the vault directly so protocol functionality is not impacted.

>  it can also potentially lead to a loss of assets. The callers who are the external protocols integrated with Tokemak's routers or Tokemak's users encounter issues when attempting to mint shares, leading to fewer assets being invested into the vault. 

This is hyperthetical and would be an issue with the caller contract that does not approve 0 before calling (as like not calling refundETH after the mint/deposit). We should also consider that most callers are EOA and non-existing integrations are OOS.


It also is declared that 
> * The more expensive the attack is for an attacker, the less likely it will be included as a Medium (holding all other factors constant).
> * The greater the cost of the attack for an attacker, the less severe the issue becomes.

To constantly call the `approve` function for an entire year will be expensive and no profit. Together with the fact that the users are not DOSed to mint/deposit because they can use the multicall (or other methods) or call the vault directly. I don't see this as a medium. Maybe more of a UX issue. It can be unDOSed at any given time and no funds are lost

Other similar issues historically deemed low:
* https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/168
* https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/206

**Comment by MarioPoneder** [comment]
Wanting to add that multiple entry points are affected, see #241.
> The following top-level methods are subject to DoS and loss of gas fee (due to failed transaction) because of the above vulnerability:
> 1.    [LMPVaultRouter(Base).mint(...)](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/vault/LMPVaultRouterBase.sol#L22-L41)
> 2.    [LMPVaultRouter(Base).deposit(...)](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/vault/LMPVaultRouterBase.sol#L43-L57) which calls LMPVaultRouterBase_.deposit(...)
> 3.    [LMPVaultRouter.withdrawToDeposit(...)](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/vault/LMPVaultRouter.sol#L26-L37) which calls LMPVaultRouterBase_.deposit(...)
>  4.   [LMPVaultRouter.swapAndDepositToVault(...)](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/vault/LMPVaultRouter.sol#L39-L60) which calls LMPVaultRouterBase_.deposit(...)
>   5.  [LMPVaultRouter.redeemToDeposit(...)](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/vault/LMPVaultRouter.sol#L62-L73) which calls LMPVaultRouterBase_.deposit(...)
>   6.  [LMPVaultRouter.depositMax(...)](https://github.com/Tokemak/v2-core-audit-2023-07-14/blob/62445b8ee3365611534c96aef189642b721693bf/src/vault/LMPVaultRouter.sol#L75-L87) which calls LMPVaultRouterBase_.deposit(...)
>
> Consequently, every user, or even worse every contract (less flexibility), that relies on one of the above methods is subject to this DoS attack.

Furthermore, the user can only reset the allowance to 0 to by (ab-)using the same approval vulnerability as the attacker which causes additional gas costs that should not be necassary in the first place.

**Comment by 0xdeadbeef0x** [comment]
Thanks! Indeed all those function end up calling deposit or mint and will revert in the described issue.

My arguments stays the same. In end, the attacker cannot create a DOS that cannot be undone. No profit for attacker and can be easily bypassed by calling approve using the routers multicall, use flashbots or call the vault directly.

I do believe this is a valid issue and should get fixed however the severity is not medium. It is very unlikely (no incentive for   attacker) and impact almost does not exist (no funds lost, a bit of griefing maybe)

**Comment by Trumpero** [comment]
Regarding this matter, I share the same view as @xiaoming9090 that it is appropriate to maintain the medium severity for this issue. 
Regarding to @0xdeadbeef0x's comment:

> The router has the capability to mint shares. The MultiCall is expected to be used not only for approve but also for other operations such as refunding excess eth. Additionally, if the protocol does want to fix the issue the router can be easily replaced without any loss of funds since the router does not hold shares. 

I am in disagreement with the assertion that Multicall is employed to perform the suitable 'approve' and then execute the 'mint' function, as there is a lack of evidence to support whether the protocol is indeed implementing this or not. Additionally, the claim that the protocol can rectify the issue by merely replacing the router is not as straightforward. If your argument holds, then numerous issues linked to denial-of-service (DOS) and contracts deployed through proxy could replace their implementations, resulting in the issue being classified as low. I don't think this is accurate.

> ALSO Its important to note that this is a router used for user convenience. A user can call the vault directly so protocol functionality is not impacted.

I believe that, across all protocols, users are expected to utilize the ROUTER to engage with the protocol rather than interacting directly with the protocol to avert unforeseen consequences.

**Comment by 0xdeadbeef0x** [comment]
Appreciate the response.

My main argument is that this is not a DOS since the service is not denied. It can be fixed immediately by calling approve. There is no loss of funds.

It does not seem to stand with Sherlock's definition of a DOS:
https://docs.sherlock.xyz/audits/judging/judging#iii.-some-standards-observed
> Could Denial-of-Service (DOS), griefing, or locking of contracts count as a Medium (or High) issue? It would not count if the DOS, etc. lasts a known, finite amount of time <1 year. If it will result in funds being inaccessible for >=1 year, then it would count as a loss of funds and be eligible for a Medium or High designation. The greater the cost of the attack for an attacker, the less severe the issue becomes.

1. The DOS does not last for +1 year - can be unDOSed immediately by calling approve or not denied at all (by multicall, flashbots or calling the vault directly
2. No funds at lost - funds are not inaccessible or lost which is what is required for a medium or high severity
3. Cost for attacker is high without any clear profit.

I think there is enough data here for making a decision

**Comment by Trumpero** [comment]
However, the question remains: who will initiate this action? From the standpoint of an ordinary user, I doubt they would be aware that they need to execute the 'approve' function before proceeding with their actions. Looking at it from the protocol's viewpoint, as I previously mentioned, it's akin to requiring the deployment of new contracts, making it a medium concern in my view. Personally, it seems more like a permanent denial-of-service (DOS) issue. 
Will leave the final decision for @hrishibhat

**Comment by 0xdeadbeef0x** [comment]
I still cannot see how it can be permanent if it can be undone immediately. 
Additionally, the profit for the attacker is unclear.

I agree it is valid and should be fixed by the protocol - but is of low severity since no funds lost and temp.
I recommend reading the decisive response in a similar issue: 
https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/168

Lets leave it to the judge

**Comment by Evert0x** [comment]
The core question is: Is this considered an indefinite DOS attack (1year+)?

It would be the case if you assume that Alice can frontrun Bob indefinitely. Currently there is no language related to this in the judging docs. 

I agree that the issue is very similar to https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/168. Current opinion is to handle the situation in a similar way. Would be accepting the escalation and close the issue.

**Comment by securitygrid** [comment]
This is a time-sensitive project and DOS one year cannot be used to judge whether this issue is valid. Prices change over time.

**Comment by Evert0x** [comment]
@securitygrid we can have another conversation in Discord to change the language of the DOS rule. But for now we should use the judging guidelines as is, because everyone acted with the assumption the current guidelines would be used to handle the judgment of issues.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

Again, open to talk about an update to the DOS rule. 

> any malicious user could perform a DOS anytime they wish

This could be language to include it in. But even with that language you can make an argument on this report that multicall can be used to mitigate the issue.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xdeadbeef0x](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/346/#issuecomment-1747606604): accepted
