### ISSUE TITLE
xiaoming90 - Rebalancing allows the deposit of underlying LP Tokens to DV during shutdown

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#574]
xiaoming90

medium

# Rebalancing allows the deposit of underlying LP Tokens to DV during shutdown
## Summary

An LMPVault that has been shut down can still deposit underlying LP tokens to destination vaults.

When the LMPVault is shut down, the vault might have migrated, been compromised by attackers, or was no longer profitable. No further "investment" to the DVs should occur in this case. Continuing to add assets/values to these vaults might lead to further loss of assets.

## Vulnerability Detail

During a shutdown, it does not allow the base asset (WETH) to flow out of the LMPVault. The only operation that is allowed is those that get the base asset (WETH) from the destination vaults back to the LMPVault as per the comment in the code below:

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/libs/LMPDebt.sol#L369

```solidity
File: LMPDebt.sol
369:     function _handleRebalanceOut(
..SNIP..
398:             } else {
399:                 // If we are shutdown then the only operations we should be performing are those that get
400:                 // the base asset back to the vault. We shouldn't be sending out more
401:                 if (params._shutdown) {
402:                     revert VaultShutdown();
403:                 }
404:                 // Working with idle baseAsset which should be in the vault already
405:                 // Just send it out
406:                 IERC20(params.tokenOut).safeTransfer(params.receiver, params.amountOut);
407:                 assetChange.idleDecrease = params.amountOut;
408:             }
409:         }
410:     }
```

However, it was observed that it is still possible to deposit the underlying (LP token) from LMPVault to destination vaults during a rebalance, which breaks the invariant.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/libs/LMPDebt.sol#L67

```solidity
File: LMPDebt.sol
67:     function rebalance(
..SNIP..
110:         // Handle increase (shares coming "In", getting underlying from the swapper and trading for new shares)
111:         if (params.amountIn > 0) {
112:             // transfer dv underlying lp from swapper to here
113:             IERC20(params.tokenIn).safeTransferFrom(msg.sender, address(this), params.amountIn);
114: 
115:             // deposit to dv (already checked in `verifyRebalance` so no need to check return of deposit)
116: 
117:             if (params.tokenIn != address(baseAsset)) {
118:                 IDestinationVault dvIn = IDestinationVault(params.destinationIn);
119:                 (uint256 debtDecreaseIn, uint256 debtIncreaseIn) =
120:                     _handleRebalanceIn(destInfoIn, dvIn, params.tokenIn, params.amountIn);
121:                 idleDebtChange.debtDecrease += debtDecreaseIn;
122:                 idleDebtChange.debtIncrease += debtIncreaseIn;
123:             } else {
124:                 idleDebtChange.idleIncrease += params.amountIn;
125:             }
126:         }
```

## Impact

When the LMPVault is shut down, the vault might have migrated, been compromised by attackers, or was no longer profitable. No further "investment" to the DVs should occur in this case. Continuing to add assets/values to these vaults might lead to further loss of assets.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/libs/LMPDebt.sol#L369

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/libs/LMPDebt.sol#L67

## Tool used

Manual Review

## Recommendation

Consider preventing the deposit of underlying (LP Tokens) to destination vaults during a shutdown.

```diff
if (params.tokenIn != address(baseAsset)) {
+	if (params._shutdown) {
+		revert VaultShutdown();
+	}
    IDestinationVault dvIn = IDestinationVault(params.destinationIn);
    (uint256 debtDecreaseIn, uint256 debtIncreaseIn) =
        _handleRebalanceIn(destInfoIn, dvIn, params.tokenIn, params.amountIn);
    idleDebtChange.debtDecrease += debtDecreaseIn;
    idleDebtChange.debtIncrease += debtIncreaseIn;
} else {
    idleDebtChange.idleIncrease += params.amountIn;
}
```

**Comment by xiaoming9090** [comment]
Escalate

Per https://docs.tokemak.xyz/protocol-information/tokemak-v2#solver:

> The solver, as the only off-chain component, proposes rebalancing solutions to the on-chain Autopilot contract for validation. Once validated as an improvement over the current asset allocation and satisfying the imposed constraints, the on-chain component can execute the solution.
>
> While Tokemak will be operating a solver starting with launch, external solvers will be enabled to participate in competitive fashion. This architecture offers a secure approach to decentralization.

This issue is not relevant to an admin mistake. The `rebalance()` function is called by solvers managed by both the protocol team & external users, not the protocol's admin. The solvers might continue to propose and carry out rebalancing against a vault that is already shutdown if this issue is not fixed, which leads to a potential loss of assets. 

Thus, this issue is a valid Medium.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Per https://docs.tokemak.xyz/protocol-information/tokemak-v2#solver:
> 
> > The solver, as the only off-chain component, proposes rebalancing solutions to the on-chain Autopilot contract for validation. Once validated as an improvement over the current asset allocation and satisfying the imposed constraints, the on-chain component can execute the solution.
> >
> > While Tokemak will be operating a solver starting with launch, external solvers will be enabled to participate in competitive fashion. This architecture offers a secure approach to decentralization.
> 
> This issue is not relevant to an admin mistake. The `rebalance()` function is called by solvers managed by both the protocol team & external users, not the protocol's admin. The solvers might continue to propose and carry out rebalancing against a vault that is already shutdown if this issue is not fixed, which leads to a potential loss of assets. 
> 
> Thus, this issue is a valid Medium.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Hello @xiaoming9090, thank you for the clarification. 
If the SOLVER is not from the protocol team, this issue can be classified as a medium issue. Currently, I am curious whether the call LMPStrategy.verifyRebalance(params) has checked the scenario mentioned by Watson since the LMPStrategy is still under development. 
I would appreciate hearing @codenutt's opinion on this issue

**Comment by codenutt** [comment]
We are still building out that LMPStrategy but it is inside of the verifyRebalance() where all of this type of validation will go. Things like:
- Validating the in/out tokens match the underlyings for the vaults targeted
- If the LMP is shutdown, only allowing rebalances back to idle
- If the destination is queued for removal, allow a greater slippage tolerance so we can exit faster
- And a dozen others

This specific one in question we've held off on adding because we need to actually expand the meaning of "shutdown" from a destination vaults perspective first. Just a binary yes/no isn't enough. For example, if we shut it down due to an exploit then we'd probably want to allow a higher degree of slippage so we can exit faster. But, if we've just deprecated it due to a pending migration, then it could just be slightly higher slippage. 

I know most of those examples are on the outflows and this specific issue is about inflows, but the validation happens all in the same area.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue closed as the context of this shutdown process is unclear. The default trust assumption is used, which is `TRUSTED` based on the contest readme.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/574/#issuecomment-1748037747): rejected
