### ISSUE TITLE
xiaoming90 - Decrease in NAV results in users being unable to exit the vault

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#586]
xiaoming90

high

# Decrease in NAV results in users being unable to exit the vault
## Summary

A decrease in NAV might result in users being unable to exit the vault.

## Vulnerability Detail

The LMPVault's `withdraw` and `redeem` functions implement the `noNavDecrease` modifier. Based on the source code's comment at Line 898 below, it was understood that the intention is to ensure that the NAV does not decrease beyond rounding tolerance. 

The problem is that it only considers rounding error but fail to take into consideration the fact that trading fee and slippage during the swapping of non-base assets to base asset (WETH) will inevitably incur some losses, which might decrease the NAV beyond the rounding tolerance, resulting in users unable to exit the vault.

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L900

```solidity
File: LMPVault.sol
147:     modifier noNavDecrease() {
148:         (uint256 oldNav, uint256 startingTotalSupply) = _snapStartNav();
149:         _;
150:         _ensureNoNavDecrease(oldNav, startingTotalSupply);
151:     }
..SNIP..
898:     /// @notice Vault nav/share shouldn't decrease on withdraw/redeem within rounding tolerance
899:     /// @dev No check when no shares
900:     function _ensureNoNavDecrease(uint256 oldNav, uint256 startingTotalSupply) private view {
901:         uint256 ts = totalSupply();
902:         if (ts == 0 || startingTotalSupply == 0) {
903:             return;
904:         }
905:         uint256 lowerBound = Math.max(oldNav, NAV_CHANGE_ROUNDING_BUFFER) - NAV_CHANGE_ROUNDING_BUFFER;
906:         uint256 newNav = (totalAssets() * MAX_FEE_BPS) / ts;
907:         if (newNav < lowerBound) {
908:             revert NavChanged(oldNav, newNav);
909:         }
910:     }
```

Assume an LMPVault with the following states:

- `totalIdle` = 0
- `totalDebt` = 50 WETH
- `totalAssets` = 50 WETH
- LMPVault consists of two (2) destination vaults (1 Balancer wstETH/sfrxETH/rETH DV and 1 Arbitrary Curve DV). Each has a debt value of 25 ETH.

Assume that Bob attempts to withdraw a certain number of LMPVault shares worth 5 WETH. Since there are insufficient idle assets on the LMPVault, it will need to burn some Balancer DV shares and exit BPT to recall the invested funds.

It is important to note that the price of Balancer DB shares/BPT is computed via the DV's `debtValue` function, which internally calls the `BalancerLPComposableStableEthOracle.getPriceInEth` function to return the fair market price of the BPT.

Based on the Balancer DV's `debtVault` function, it is determined that $x$ number of BPT is worth 5 WETH. In this case, $x$ BPT is proportionally exited, and the Balancer DV received back three different tokens (wstETH/sfrxETH/rETH). Since they are not the base asset (WETH), all three tokens need to be swapped to the base asset (WETH) via the configured DEX (e.g., Uniswap). At least three swaps (might be more if multi-routes are configured) must be executed. 

Let $y_{weth}$ be the number of base assets (WETH) received from the swaps. Swap or trade will always incur trading fees and slippage. As a result, the base asset (WETH) received back from the swaps is definitely less than 5 WETH ($y_{weth} < 5\ {eth}$), which entails a decrease in NAV. If the decrease goes beyond the configured rounding tolerance, users will not be able to exit the vaults.

## Impact

Users might be unable to exit the vault.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L900

## Tool used

Manual Review

## Recommendation

Review if it is crucial to have the `noNavDecrease` modifier. If not, consider removing them. Otherwise, the modifier should take into consideration a possible drop in NAV due to the slippage and trading fee incurred while swapping from non-base assets to base assets and determine if it falls within the acceptable limit.

**Comment by xiaoming9090** [comment]
Escalate

The main point of this report is to demonstrate the risks of the `noNavDecrease` modifier. It is a valid issue as long as there is a risk in its current design. It is not about whether the `noNavDecrease` modifier is working correctly or not OR working as per design.

For the users to be able to withdraw later, as mentioned in the judging comment, the market condition market must improve. However, it is incorrect to assume that the market condition will always improve, as it might go downhill and never recover. As such, there must be measures in place to allow users to continue to withdraw their assets under such scenarios, as mentioned in my solution. Otherwise, their assets will be permanently stuck.

Thus, this is a valid High issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The main point of this report is to demonstrate the risks of the `noNavDecrease` modifier. It is a valid issue as long as there is a risk in its current design. It is not about whether the `noNavDecrease` modifier is working correctly or not OR working as per design.
> 
> For the users to be able to withdraw later, as mentioned in the judging comment, the market condition market must improve. However, it is incorrect to assume that the market condition will always improve, as it might go downhill and never recover. As such, there must be measures in place to allow users to continue to withdraw their assets under such scenarios, as mentioned in my solution. Otherwise, their assets will be permanently stuck.
> 
> Thus, this is a valid High issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by midori-fuse** [comment]
Escalate

If this ends up being valid, #518 should be a dupe of this

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> If this ends up being valid, #518 should be a dupe of this

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@Trumpero From the escalation comments it seems like a valid issue. Do you have additional comments?

**Comment by Trumpero** [comment]
The `noNavDecrease` modifier is used to ensure that the withdrawal does not significantly decrease the NAV. This condition is necessary safeguard the vault from potential harm from withdrawing by checking the NAV value of the vault. It only checks with the result of withdraw, so it will not be affected by market turbulence or swap manipulation because `withdraw` function will revert beforehand in that case.

If the market consistently goes down, this modifier doesn't have any effect because the swap needs to pass all slippage checks and safeguards of the `withdraw` and `_withdraw` functions first. Thus, the scenario that the swap incurs high trading fees and slippage doesn't revert in this modifier. The reversion occurs in the `withdraw` and `_withdraw` functions beforehand, resulting in the risk of being unable to withdraw due to too strict slippage check, as mentioned in issue #519. 
 Therefore, I believe this issue is invalid, and `noNavDecrease` doesn't have any vulnerabilities.
 
 @codenutt Could you please review this?

**Comment by floranguyen0** [comment]
"It only checks with the result of withdraw, so it will not be affected by market turbulence or swap manipulation because withdraw function will revert beforehand in that case.

If the market consistently goes down, this modifier doesn't have any effect because the swap needs to pass all slippage checks and safeguards of the withdraw and _withdraw functions first. Thus, the scenario that the swap incurs high trading fees and slippage doesn't revert in this modifier. The reversion occurs in the withdraw and _withdraw functions beforehand..."

It is indeed affected by market turbulence and withdraw() will not revert beforehand. You can refer to my POC #518 (it is redeem() that was used in the poc, but if we use withdraw(), it will revert because of the same reason `NavChanged`).

**Comment by codenutt** [comment]
The debt removed from totalDebt during a withdraw should always be in proportion to shares burned regardless of the number of assets actually returned to the user. The number that's checked in that modifier is nav/share, not nav itself.

**Comment by xiaoming9090** [comment]
The modifier measures the deviation of the NAV per share (`totalAssets` divided by `totalSupply`) during withdrawal.

This report is based on the assumption that the reduced number of assets returned to the user due to trading fees and slippage incurred during the swaps would impact the NAV per share. However, this is incorrect based on the sponsor's [latest remark](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/586#issuecomment-1773205942). The [`totalAssets`](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L304) is computed by adding up `totalIdle` and `totalDebt`. The amount of `totalDebt` deducted is independent of the number of assets returned to the users.

Thus, this report is invalid. @Evert0x @Trumpero please proceed to invalid this report and escalation.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/586/#issuecomment-1748036367): rejected
- [midori-fuse](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/586/#issuecomment-1748225061): rejected
