### ISSUE TITLE
Bauchibred - Inability to deploy or add liquidity to composable balancer pools

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokemak-judging#894]
Bauchibred

medium

# Inability to deploy or add liquidity to composable balancer pools

## Summary

While attempting to add liquidity to a balancer pool the current implementation of `_getJoinPoolRequest()` will cause the lengths of `amountUser/amounts` be different if the pool is a composable pool. However, when calling Balancer's `joinPool`, if `JoinKind` is EXACT_TOKENS_IN_FOR_BPT_OUT, then `maxAmountsIn`/`assets`/`amountsIn`in [userData](https://docs.balancer.fi/reference/joins-and-exits/pool-joins.html#userdata) **must have** the same length in [IBalancerVault.JoinPoolRequest](https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/interfaces/balancer/IBalancerVault.sol#L27-L32), otherwise the transaction will revert.

## Vulnerability Detail

Take a look at the [addLiquidity()](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L88-L139) function, under the hood it calls the internal `_getJoinPoolRequest()` to generate the request for joining balancer's pool

```solidity
    function addLiquidity(
        IVault vault,
        address pool,
        address[] calldata tokens,
        uint256[] calldata exactTokenAmounts,
        uint256 minLpMintAmount
    ) public {
...ommitted for brevity

        vault.joinPool(
            poolId,
            address(this), // sender
            address(this), // recipient of BPT token
            _getJoinPoolRequest(pool, tokens, exactTokenAmounts, minLpMintAmount)
        );

...ommitted for brevity
    }
```

Now [`_getJoinPoolRequest()`"s](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L424-L457) current implementation reduces the size of the array by one if the pool is a composable one

```solidity
    function _getJoinPoolRequest(
        address pool,
        address[] memory tokens,
        uint256[] calldata amounts,
        uint256 poolAmountOut
    ) private view returns (IVault.JoinPoolRequest memory joinRequest) {
        uint256[] memory amountsUser;


        if (BalancerUtilities.isComposablePool(pool)) {
            uint256 nTokens = tokens.length;
            uint256 uix = 0;
            uint256 bptIndex = IBalancerComposableStablePool(pool).getBptIndex();
            //@audit
            amountsUser = new uint256[](nTokens - 1);
            for (uint256 i = 0; i < nTokens; i++) {
                if (i != bptIndex) {
                    amountsUser[uix] = amounts[i];
                    uix++;
                }
            }
        } else {
            amountsUser = amounts;
        }


        joinRequest = IVault.JoinPoolRequest({
            assets: tokens,
            maxAmountsIn: amounts, // maxAmountsIn,
            userData: abi.encode(
                IVault.JoinKind.EXACT_TOKENS_IN_FOR_BPT_OUT,
                amountsUser, //maxAmountsIn,
                poolAmountOut
                ),
            fromInternalBalance: false
        });
    }
```

But the code for joining with [the kind "EXACT_TOKENS_IN_FOR_BPT_OUT"](https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/BaseWeightedPool.sol#L274) from balancer's codebase specifically requires that arrays provided for the amounts from the userData must be the same, therefore, when this is not the case it will be reverted.

## Impact

User can't deploy or add liquidity to a composable pool on balancer

## Code Snippet
(https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L424-L457
## Tool used

Manual Audit

## Recommendation

Ensure that the amounts array lengths match.

**Comment by Bauchibred** [comment]
Escalate

Reason for escalation is that I disagree with judge's comment of this being a low because the `addLiquidity()` is not used in any contracts.

The whole destination adapters are in scope.

Checking out the [readMe from the  destination adapters section](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/README.md)  we can see that the adapters are used for different important things with one of their uses being the below:
> Each Adapter targets specific exchange and aims to support one of the three basic operations: to provide liquidity, withdraw or manage the rewards (claiming).

This report obviously proves that there is a break in a core functionality which warrants to be a valid medium.

Asides the fact that this breaks a core functionality, other factors to support my argument are listed below:

- In the 2023-04-splits contest, there was an issue caused by a library function that is not called by any contract in the scope that was validated as a medium.
- Additionally, from the test codes we can see that `addLiquidity()` would be used.


> Note: In the summary of the report a wrong link was attached and this ["IBalancerVault.JoinPoolRequest"](https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/interfaces/balancer/IBalancerVault.sol#L27-L32) should be this instead ["IVault.JoinPoolRequest"](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L447-L456) as correctly stated in the _Vulnerability Details_ section.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Reason for escalation is that I disagree with judge's comment of this being a low because the `addLiquidity()` is not used in any contracts.
> 
> The whole destination adapters are in scope.
> 
> Checking out the [readMe from the  destination adapters section](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/README.md)  we can see that the adapters are used for different important things with one of their uses being the below:
> > Each Adapter targets specific exchange and aims to support one of the three basic operations: to provide liquidity, withdraw or manage the rewards (claiming).
> 
> This report obviously proves that there is a break in a core functionality which warrants to be a valid medium.
> 
> Asides the fact that this breaks a core functionality, other factors to support my argument are listed below:
> 
> - In the 2023-04-splits contest, there was an issue caused by a library function that is not called by any contract in the scope that was validated as a medium.
> - Additionally, from the test codes we can see that `addLiquidity()` would be used.
> 
> 
> > Note: In the summary of the report a wrong link was attached and this ["IBalancerVault.JoinPoolRequest"](https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/interfaces/balancer/IBalancerVault.sol#L27-L32) should be this instead ["IVault.JoinPoolRequest"](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/BalancerBeethovenAdapter.sol#L447-L456) as correctly stated in the _Vulnerability Details_ section.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by huuducsc** [comment]
Thanks for the feedback, but I disagree with the escalation. Here are the reasons why I believe this issue should be considered as a low:

1. The `addLiquidity` function of that library isn't used in any contracts except for the tests. So I believe this function may serve as a helper function for only testing or as a feature to be utilized in the future. However, Sherlock has stated that this case is not considered valid in the validity criteria.
> Future issues: Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues.

https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid

2. The issue has a low impact since it doesn't result in any loss of funds or harm to the protocol. Users are simply unable to deploy or add liquidity to a composable pool on Balancer by using a contract that ultilized this library.

**Comment by Trumpero** [comment]
Thanks for the feedback, but I disagree with the escalation. Here are the reasons why I believe this issue should be considered as a low:

1. The `addLiquidity` function of that library isn't used in any contracts except for the tests. So I believe this function may serve as a helper function for only testing or as a feature to be utilized in the future. However, Sherlock has stated that this case is not considered valid in the validity criteria.
> Future issues: Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues.

https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid

2. The issue has a low impact since it doesn't result in any loss of funds or harm to the protocol. Users are simply unable to deploy or add liquidity to a composable pool on Balancer by using a contract that ultilized this library.

**Comment by Bauchibred** [comment]
> Responding further in light of the [additional comment request](https://discord.com/channels/812037309376495636/1130514263522410506/1164072538687672350) by @hrishibhat.

I appreciate the judge taking another look at the report. However, I disagree with their assessment and continue to stand by my initial escalation. 

To address the first point: as previously noted, this is a core functionality that is explicitly mentioned in the  [documentation/ReadMe](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/README.md) section for the destination adapters. 

On the second point, while using past issues as a reference, [here's an example](https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/120#issuecomment-1587670113). Even though they are only somewhat similar, I believe the referenced issue was  validated as medium — not because it leads to a loss of funds, but due to a disruption in a core functionality.

**Comment by Trumpero** [comment]
This function isn't used in any of Tokemak's contracts, so it can't be considered as 'core functionality'. The highest impact of this issue is related to external integration (which is out of scope) or future issues and it doesn't cause any loss. Therefore, this should be a low/info.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue invalid based on last comment of the lead judge.

> To address the first point: as previously noted, this is a core functionality that is explicitly mentioned in the [documentation/ReadMe](https://github.com/sherlock-audit/2023-06-tokemak/blob/5d8e902ce33981a6506b1b5fb979a084602c6c9a/v2-core-audit-2023-07-14/src/destinations/adapters/README.md) section for the destination adapters.

If the section was explicitly mentioned in the contest README it would have a strong argument to be valid. But this documentation is just describing the functionality, which is nice to have for tests.

**Comment by Bauchibred** [comment]
> If the section was explicitly mentioned in the contest README it would have a strong argument to be valid. But this documentation is just describing the functionality, which is nice to have for tests.

This brings a different angle to the argument and I stand corrected, I now understand how this could be considered low/info.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Bauchibred](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/894/#issuecomment-1749018828): rejected
